services:
  app:
    image: frontend-fs12
    build:
      context: ./todo-frontend/. # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    container_name: frontend-production # This will name the container hello-front-dev
    environment: 
      - VITE_BACKEND_URL=http://localhost:8080/api
    depends_on:
      - backend # wait for the backend container to be started


  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - backend # wait for the backend container to be started


  backend:
    image: backend-fs
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: initialized-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrpoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis:8
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data


volumes:
  mongo_data:
  redis_data:

  
