services:
  backend:
    image: backend-fs
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database
      - REDIS_URL=redis://redis:6379

  
